### ISSUE TITLE
为啥将 https://paperswithcode.com/sota/conversational-response-selection-on-douban-1榜单上的结果撤了？

### ISSUE THREAD

**Issue by wulaoshi** [gmftbyGMFTBY/SimpleReDial-v1#1]
RT，上次看该类榜单还是榜一，最近怎么 DR-BERT 结果都没了

**Comment by gmftbyGMFTBY** [comment]
感谢您的关注，目前该工作在投稿中，为了避免影响双盲评审，慎重之下还是暂时删除了paperwithcode上的结果


| |
GMFTBY
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月24日 ***@***.***> 写道：

RT，上次看该类榜单还是榜一，最近怎么 DR-BERT 结果都没了

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
